language: julia

os:
  - linux

julia:
  - 1.3

branches:
  only:
    - master
    - test-remove-gfortran
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

before_install:
  - if [ `uname` == "Linux" ]; then unset DY_LIBRARY_PATH; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
