language: julia

os:
  - linux

arch:
  - x64
  - amd64

julia:
  - 1.3

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt_packages:
    - gfortran

before_install:
  - if [ `uname` == "Linux" ]; then unset DY_LIBRARY_PATH; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
